config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get :dashboards, to: 'dashboards#profile'
  get :profile, to: 'dashboards#my_profile'

  resources :pokemons do
    resources :bookings, only: %i[new create]
  end

  resources :bookings do
    member do
      patch '/accepted', to: 'bookings#accepted'
      patch '/denied', to: 'bookings#denied'
      patch '/cancelled', to: 'bookings#cancelled'
    end
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top" data-controller="navbar" data-action="scroll@window->navbar#updateNavbar">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://res.cloudinary.com/dlwr1bikm/image/upload/c_thumb,w_200,g_face/v1645468631/development/Pikachu-PNG-Transparent-Image_ca3xv5.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>

          <li class="nav-item dropdown">
            <%= cl_image_tag current_user.photo.key, crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <% if policy(Pokemon).create? %>
                <%= link_to "Add a new Pokemon", new_pokemon_path, class: "dropdown-item" %>
              <% end %>
              <%= link_to "My Dahsboard", dashboards_path, class: "dropdown-item" %>
              <%= link_to "My Profile", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_search.html.erb
  <%# <% <%= f.input :query %>
  <%# <%= f.submit %>

 <div class="search-form-control form-group">
    <%= simple_form_for :search, url: pokemons_path, method: :get do |f| %>
      <div class="d-flex query-selectors">
        <%= f.input :address, placeholder: "Add a city...",class: "form-control string required", label: false %>
        <%= f.input :personalities, class: "js-example-placeholder-single form-control",label: false, collection: Pokemon::POKEMON_PERSONALITIES, input_html:  {multiple: true, data: { placeholder: "Select categories...", controller: 'select2', select2_options_value: {tags: true}}} %>
        <%# <%= f.submit "Search", class: "btn btn-flat" %>
        <button type="submit" class="btn btn-flat" name="commit" data-disable-with="Search" >
          <i class="fas fa-search"></i>
        </button>
      </div>
    <% end %>
</div>

<%# <input type="submit" name="commit" value="Search" class="btn btn-flat" data-disable-with="Search"> %>