config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get :dashboards, to: 'dashboards#profile'
  get :profile, to: 'dashboards#my_profile'

  resources :pokemons do
    resources :bookings, only: %i[new create]
  end

  resources :bookings do
    member do
      patch '/accepted', to: 'bookings#accepted'
      patch '/denied', to: 'bookings#denied'
      patch '/cancelled', to: 'bookings#cancelled'
    end
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def profile
    authorize(:dashboard, :profile?)
    @pokemons = current_user.pokemons
    @bookings = current_user.bookings
    @user = current_user
    @booking_pokemons_user = Booking.all.select { |booking| booking.pokemon.user == @user }
    @demand_pending_user = select("pending")
    @demand_accepted_user = select("accepted")
  end

  def my_profile
    skip_authorization
  end

  private

  def select(state)
    @booking_pokemons_user.select { |booking| booking.user != current_user && booking.status == state }
  end
end

app/views/dashboards/profile.html.erb
<div class="page-banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dlwr1bikm/image/upload/v1645468248/development/background_pokemon_mifddl.png);">
  <div class="container">
    <h1>Hi <strong><%= @user.first_name.capitalize %></strong></h1>
    <p>Welcome to your dashboard</p>
    <%# <a class="btn btn-flat" href="#">Apply now</a> %>
    <%= link_to edit_user_registration_path do %>
     <%= cl_image_tag current_user.photo.key, crop: :fill, width: 200, class: "user-img-dashboard"%>
    <% end %>
  </div>
</div>

<div class="container">
  <%# Liste des demandes de locations pour mes pokemons %>
    <h2 class="text-left cards-home-title mt-5"><strong>Demands</strong> for my Pokemons</h2>
    <div class="row">
      <div class="pending-bookings col-12 col-lg-6">
        <h4 class="text-left mt-2">Pending(<%= @demand_pending_user.count %>)</h6>
          <div class="dropdown-divider"></div>
            <% @demand_pending_user.each do |booking| %>
                <div class="card-dashboard my-3">
                  <%= cl_image_tag booking.pokemon.photo.key, height: 300, width: 120 %>
                  <div class="card-dashboard-infos">
                    <h2>My <%= booking.pokemon.name %></h2>
                    <p>From: <strong><%= booking.begin_date.strftime("%m/%d/%Y") %></strong></p>
                    <p>To: <strong><%= booking.end_date.strftime("%m/%d/%Y") %></strong></p>
                    <div class="dropdown-divider my-2"></div>
                    <p class="mb-3">Requester: <strong><%= booking.user.first_name %> <%= booking.user.last_name %></strong></p>
                    <%= link_to 'Accept', accepted_booking_path(booking), method: :patch, class: "btn-green link-no-deco mx-3 my-2" %>
                    <%= link_to 'Refuse', denied_booking_path(booking), method: :patch, class: "btn-red link-no-deco" %>
                  </div>
                  <div class="car-product-pricing">
                    <p>Total price:</p>
                    <h2>€<%= booking.total_price %></h2>
                  </div>
                </div>
          <% end %>
      </div>
      <div class="accepted-bookings col-12 col-lg-6">
        <h4 class="text-left mt-2">Coming(<%= @demand_pending_user.count %>)</h6>
          <div class="dropdown-divider"></div>
            <% @demand_accepted_user.each do |booking| %>
                <div class="card-dashboard my-3">
                  <%= cl_image_tag booking.pokemon.photo.key, height: 300, width: 120 %>
                  <div class="card-dashboard-infos">
                    <h2>My <%= booking.pokemon.name %></h2>
                    <p>From: <strong><%= booking.begin_date.strftime("%m/%d/%Y") %></strong></p>
                    <p>To: <strong><%= booking.end_date.strftime("%m/%d/%Y") %></strong></p>
                    <div class="dropdown-divider my-2"></div>
                    <p class="mb-3">Requester: <strong><%= booking.user.first_name %> <%= booking.user.last_name %></strong></p>
                  </div>
                  <div class="car-product-pricing">
                    <p>Total price:</p>
                    <h2>€<%= booking.total_price %></h2>
                  </div>
                </div>
          <% end %>
      </div>
    </div>

  <%# Liste de mes demandes de locations %>
    <h2 class="text-left cards-home-title my-5"><strong>Requests</strong></h2>
    <div class="row">
      <div class="pending-bookings col-12 col-lg-6">
        <h4 class="text-left mt-2">Pending(<%= @bookings.where(status: "pending").count %>)</h6>
          <div class="dropdown-divider"></div>
            <% @bookings.where(status: "pending").each do |booking|  %>
                <div class="card-dashboard my-3">
                  <%= cl_image_tag booking.pokemon.photo.key, height: 300, width: 120 %>
                  <div class="card-dashboard-infos">
                    <h2><%= booking.pokemon.name %></h2>
                    <p>Start Date: <strong><%= booking.begin_date.to_date %></strong></p>
                    <p>End Date: <strong><%= booking.end_date.to_date %></strong></p>
                    <div class="dropdown-divider my-2"></div>
                    <p class="mb-3">Status: <strong><%= booking.status.capitalize %></strong></p>
                    <%= link_to 'Cancel', cancelled_booking_path(booking), method: :patch, class: "btn-cancel link-no-deco" %>
                  </div>
                  <div class="car-product-pricing">
                    <p>Total price:</p>
                    <h2>€<%= booking.total_price %></h2>
                  </div>
                </div>
          <% end %>
      </div>
      <div class="accepted-bookings col-12 col-lg-6">
        <h4 class="text-left mt-2">Coming(<%= @bookings.where(status: "accepted").count %>)</h6>
          <div class="dropdown-divider"></div>
            <% @bookings.where(status: "accepted").each do |booking|  %>
                <div class="card-dashboard my-3">
                  <%= cl_image_tag booking.pokemon.photo.key, height: 300, width: 120 %>
                  <div class="card-dashboard-infos">
                    <h2><%= booking.pokemon.name %></h2>
                    <p>Start Date: <strong><%= booking.begin_date.to_date %></strong></p>
                    <p>End Date: <strong><%= booking.end_date.to_date %></strong></p>
                    <div class="dropdown-divider my-2"></div>
                    <p class="mb-3">Status: <strong><%= booking.status.capitalize %></strong></p>
                  </div>
                  <div class="car-product-pricing">
                    <p>Total price:</p>
                    <h2>€<%= booking.total_price %></h2>
                  </div>
                </div>
          <% end %>
      </div>
    </div>
  <%# Liste de mes pokemons %>
    <h2 class="text-left cards-home-title my-5">All my <strong>Pokemons</strong> (<%= @pokemons.count %>)</h2>
      <div class="cards p-0">
        <% @pokemons.each do |pokemon| %>
        <div class="cross-div">
          <%= link_to pokemon, class: "link-no-deco" do %>
              <div class="card-product my-3">
                <%= cl_image_tag pokemon.photo.key, height: 300, width: 120 %>
                <div class="card-product-infos">
                  <h2><%= pokemon.name %></h2>
                  <p>Type: <strong><%= pokemon.element.capitalize%></strong></p>
                  <div class="dropdown-divider my-2"></div>
                  <p><i class="fa-solid fa-venus-mars"></i> <%= pokemon.gender.capitalize %></p>
                  <p><strong><%= pokemon.height.round %></strong>cm | <strong><%= pokemon.weight.round %></strong>kg</p>
                  <p>Personality: <strong><%= pokemon.personality.capitalize%></strong></p>
                </div>
                <div class="car-product-pricing">
                  <h2>€<%= pokemon.day_price %></h2>
                  <p>/per day</p>
                </div>
              </div>
              <%= link_to pokemon_path(pokemon),
                method: :delete,
                data: { confirm: "Are you sure?" } do %>
                <%# <i class=“far fa-times-circle”></i> %>
                <i class="fa-solid fa-circle-xmark"></i>
              <% end %>
            <% end %>
        </div>
        <% end %>
      </div>
    </div>
</div>
</div>