config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get :dashboards, to: 'dashboards#profile'
  get :profile, to: 'dashboards#my_profile'

  resources :pokemons do
    resources :bookings, only: %i[new create]
  end

  resources :bookings do
    member do
      patch '/accepted', to: 'bookings#accepted'
      patch '/denied', to: 'bookings#denied'
      patch '/cancelled', to: 'bookings#cancelled'
    end
  end
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  # const
  POKEMON_TYPES = %w[bug dragon fairy fire ghost ground normal psychic steel dark electric fighting flying grass ice poison rock water]
  FRENCH_POKEMON_TYPES = %w[insecte dragon fée feu spectre sol normal psy acier ténèbre électrik combat vol plante glace poison roche eau]
  POKEMON_GENDERS = %w[male female asexual]
  POKEMON_PERSONALITIES = %w[brave calm quiet docile rash gentle careful relaxing timid athlete smart]
  POKEMON_STREET = ["rue de l'eglise", "Place de l'eglise", "Grande Rue", "Rue du Moulin", "Place de la Mairie", "Rue du Château", "Rue des Écoles", "Rue de la Gare", "Rue de la Mairie", "rue principale"]
  POKEMON_CITY = %w[Paris Marseille Lyon Toulouse Nice Nantes Montpellier Strasbourg Bordeaux Lille Rennes Reims Saint-Étienne Toulon Grenoble Dijon Angers Nîmes Villeurbanne Bruxelles Barcelone Berlin Liège Bruges Anvers]

  belongs_to :user
  # ActiveStorage Cloudinary
  has_one_attached :photo

  has_many :bookings, dependent: :destroy
  # Validates
  validates :name, :day_price, :gender, :element, :personality, presence: true
  validates :element, inclusion: { in: POKEMON_TYPES, message: "Please select a type from the list" }
  validates :gender, inclusion: { in: POKEMON_GENDERS, message: "Please select a valid gender" }
  validates :personality, inclusion: { in: POKEMON_PERSONALITIES, message: "Please select a valid personality" }
  validates :height, :weight, numericality: { greater_than: 0 }
  validates :day_price, numericality: { only_integer: true }

  before_save :attach_photo

  def attach_photo
    return if photo.attached?
    self.photo.attach(io: File.open(File.join(Rails.root,'app/assets/images/poke.png')), filename: 'poke')
  end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @pokemons = policy_scope(Pokemon).order(created_at: :desc)

    if params[:search].present?
      if search_params[:personalities].reject(&:empty?).present? && search_params[:address].present?
        @pokemons = policy_scope(Pokemon).order(created_at: :desc)
                                         .where(personality: search_params[:personalities].reject(&:empty?))
                                         .and(policy_scope(Pokemon).where("address ILIKE ?", "%#{search_params[:address]}%"))

      elsif search_params[:personalities].reject(&:empty?).present? && !search_params[:address].present?
        @pokemons = policy_scope(Pokemon).order(created_at: :desc)
                                         .where(personality: search_params[:personalities].reject(&:empty?))

      elsif !search_params[:personalities].reject(&:empty?).present? && search_params[:address].present?
        @pokemons = policy_scope(Pokemon).order(created_at: :desc)
                                         .where("address ILIKE ?", "%#{search_params[:address]}%")
      end

    else
      @pokemons = policy_scope(Pokemon).order(created_at: :desc)
    end

    @markers = @pokemons.geocoded.map do |pokemon|
      {
        lat: pokemon.latitude,
        lng: pokemon.longitude,
        info_window: render_to_string(partial: "info_window", locals: { pokemon: pokemon }),
        image_url: helpers.asset_url("poke.png")
      }
    end
  end

  def show
    @pokemon = Pokemon.find(params[:id])
    @user = @pokemon.user
    @booking = Booking.new
    @booking.pokemon = @pokemon
    authorize @booking
    authorize @pokemon
  end

  def new
    @pokemon = Pokemon.new
    authorize @pokemon
  end

  def create
    @pokemon = Pokemon.new(pokemon_params)
    @pokemon.user = current_user
    authorize @pokemon
    if @pokemon.save
      redirect_to pokemon_path(@pokemon)
    else
      render :new
    end
  end

  def edit
    @pokemon = Pokemon.find(params[:id])
    authorize @pokemon
  end

  def update
    @pokemon = Pokemon.find(params[:id])
    @pokemon.update(pokemon_params)
    authorize @pokemon
    redirect_to pokemon_path(@pokemon)
  end

  def destroy
    @pokemon = Pokemon.find(params[:id])
    @pokemon.destroy
    authorize @pokemon
    redirect_to dashboards_path
  end

  private

  def pokemon_params
    params.require(:pokemon).permit(:name, :day_price, :height, :weight, :gender, :element, :personality, :description, :photo, :address)
  end

  def search_params
    params.require(:search).permit(:address, personalities:[])
  end
end

app/views/pokemons/_info_window.html.erb
<h2 class='text-warning'><%= pokemon.name %></h2>
<p><%= pokemon.address %></p>
 <%= cl_image_tag pokemon.photo.key, height: 75, width: 75, crop: :fit %>

app/views/pokemons/edit.html.erb
<div class="page-banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dlwr1bikm/image/upload/v1645473081/development/pokemon-user-background_fkkm6k.png);">
  <div class="container">
    <h1><strong>Update</strong> my Pokemon</h1>
    <p>Please feel free to add or update your pokemon's information</p>
    <%# <a class="btn btn-flat" href="#">Apply now</a> %>
  </div>
</div>

<div class="container">
  <div class="col-6 offset-3 mt-3">
    <%= simple_form_for(@pokemon) do |f| %>
      <div class="form-group">
        <%# <h3>Information about your Pokemon</h3> %>
          <%= f.input :name %>
          <div class="row">
            <div class="col">
              <%= f.input :height, placeholder: "cm", input_html: { min: '0' } %>
            </div>
            <div class="col">
              <%= f.input :weight, placeholder: "kg", input_html: { min: '0' } %>
            </div>
          </div>
          <div class="row">
            <div class="col">
              <%= f.input :gender, collection: Pokemon::POKEMON_GENDERS %>
            </div>
            <div class="col">
              <%= f.input :element, collection: Pokemon::POKEMON_TYPES%>
            </div>
          </div>
          <%= f.input :personality, collection: Pokemon::POKEMON_PERSONALITIES %>
          <%= f.input :address,
              input_html: { data: { geocoder_target: "address" } },
              wrapper_html: { data: { controller: "geocoder", geocoder_api_key_value: ENV['MAPBOX_API_KEY'] } } %>

          <%= f.input :photo, as: :file %>
      </div>
      <div class="dropdown-divider my-3"></div>
      <div class="form-group">
        <h3>Your rental offer</h3>
        <div class="input-group">
          <div class="input-group-prepend">
            <span class="input-group-text">€</span>
          </div>
          <%= f.input :day_price, placeholder: 'Price per day', label: false,input_html: { class: "form-control", min: '0' }, hint: "You can change it in the future"  %>
        </div>
        <%= f.input :description, label: "All additionnal information", placeholder: "Policies, rent time, rules, etc" %>
      </div>
      <%= f.submit "Edit my pokemon", class: "btn btn-flat mb-4" %>
    <% end %>
  </div>
</div>

app/views/pokemons/index.html.erb
<div class="page-banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dlwr1bikm/image/upload/v1645473081/development/pokemon-user-background_fkkm6k.png);">
  <div class="container">
    <h1>Available <strong>Pokemons</strong></h1>
    <p>Find your ideal companion </p>
    <%# <a class="btn btn-flat" href="#">Apply now</a> %>
  </div>
</div>

<div class="cards-container">
  <div class="cards">
    <% @pokemons.each do |pokemon| %>
      <%= link_to pokemon, class: "link-no-deco" do %>
        <div class="card-index my-3">
          <%= cl_image_tag pokemon.photo.key, height: 300, width: 120 %>
          <div class="card-index-infos">
            <h2><%= pokemon.name.capitalize %></h2>
            <p>Type: <strong><%= pokemon.element.capitalize%></strong></p>
            <div class="dropdown-divider my-2"></div>
            <p><i class="fa-solid fa-venus-mars"></i> <%= pokemon.gender.capitalize %></p>
            <p><strong><%= pokemon.height.round %></strong>cm | <strong><%= pokemon.weight.round %></strong>kg</p>
            <p>Personality: <strong><%= pokemon.personality.capitalize%></strong></p>
          </div>
          <div class="car-index-pricing">
            <h2>€<%= pokemon.day_price %></h2>
            <p>/per day</p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div id="map"
  data-controller="mapbox"
  data-mapbox-markers-value="<%= @markers.to_json %>"
  data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/pokemons/new.html.erb
<div class="page-banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dlwr1bikm/image/upload/v1645473081/development/pokemon-user-background_fkkm6k.png);">
  <div class="container">
    <h1><strong>Add</strong> my Pokemon</h1>
    <p>Please fill in all the information</p>
    <%# <a class="btn btn-flat" href="#">Apply now</a> %>
  </div>
</div>

<div class="container">
  <div class="col-6 offset-3 mt-3">
    <%= simple_form_for(@pokemon) do |f| %>
      <div class="form-group">
        <h3>Information about your Pokemon</h3>
          <%= f.input :name %>
          <div class="row">
            <div class="col">
              <%= f.input :height, placeholder: "cm", input_html: { min: '0' } %>
            </div>
            <div class="col">
              <%= f.input :weight, placeholder: "kg", input_html: { min: '0' } %>
            </div>
          </div>
          <div class="row">
            <div class="col">
              <%= f.input :gender, collection: Pokemon::POKEMON_GENDERS %>
            </div>
            <div class="col">
              <%= f.input :element, collection: Pokemon::POKEMON_TYPES%>
            </div>
          </div>
          <%= f.input :personality, collection: Pokemon::POKEMON_PERSONALITIES %>
          <%= f.input :address,
              input_html: { data: { geocoder_target: "address" } },
              wrapper_html: { data: { controller: "geocoder", geocoder_api_key_value: ENV['MAPBOX_API_KEY'] } } %>

          <%= f.input :photo, as: :file %>
      </div>
      <div class="dropdown-divider my-3"></div>
      <div class="form-group">
        <h3>Your rental offer</h3>
        <div class="input-group">
          <div class="input-group-prepend">
            <span class="input-group-text">€</span>
          </div>
          <%= f.input :day_price, placeholder: 'Price per day', label: false,input_html: { class: "form-control", min: '0' }, hint: "You can change it in the future"  %>
        </div>
        <%= f.input :description, label: "All additionnal information", placeholder: "Policies, rent time, rules, etc" %>
      </div>
      <%= f.submit "Add my pokemon", class: "btn btn-flat mb-4" %>
    <% end %>
  </div>
</div>

app/views/pokemons/show.html.erb
<div class="profil-banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dlwr1bikm/image/upload/v1645473081/development/pokemon-user-background_fkkm6k.png);">
  <div class="container">
    <h1>Hi, I'm <strong><%= @pokemon.name %></strong></h1>
    <p>You can find more information about me below</p>
    <%# <a class="btn btn-flat" href="#">Apply now</a> %>
    <%# <%= link_to "Book me", new_pokemon_booking_path(@pokemon), class: "btn btn-flat" %>
    <%= link_to "Back", pokemons_path, class: "btn btn-ghost-white" %>
    </div>
  </div>
</div>

<div class="container">

  <div class="row my-5">
    <div class="pokemon-infos col-sm-12 col-md-8">
      <div>
      <%= cl_image_tag @pokemon.photo.key, width: 200 %>
      </div>
      <div class="basic-infos">
        <h4 class="mb-4"> <mark class="p-2"><strong><%= @pokemon.name.capitalize%></strong> </mark></h4>
        <p><i class="fa-solid fa-venus-mars"></i> <%= @pokemon.gender.capitalize %></p>
         <p><i class="fa-solid fa-up-down"></i> <%= @pokemon.height.round %>cm</p>
         <p><i class="fa-solid fa-weight-scale"></i> <%= @pokemon.weight.round %>kg</p>
      </div>
      <div class="details-infos">
        <p>Type: <strong><%= @pokemon.element.capitalize%></strong></p>
        <p>Personality: <strong><%= @pokemon.personality.capitalize%></strong></p>
        <p>Owner: <strong><%= @user.first_name %></strong> <strong><%= @user.last_name.capitalize %></p></strong>
        <p>Description: <strong><%= @pokemon.description.capitalize%></strong></p>
        <!-- <h4 id="pokemon-price">€<%= @pokemon.day_price %><small>/ per day</small></h2>-->

      </div>
    </div>
      <% if @pokemon.user == current_user %>
        <div class="booking-form col-sm-12 col-md-4">
        <h3 class="mb-2">I'm yours, missed me ?</h3>
        <p>You can update my information.</p>
          <div class="row justify-content-center">
            <div class="col-sm-12 col-md-4">
              <%= link_to "Edit", edit_pokemon_path(@pokemon), class:'btn-cancel link-no-deco' %>
            </div>
            <div class="col-sm-12 col-md-4">
              <%= link_to "Delete", pokemon_path(@pokemon),
                  method: :delete,
                  data: { confirm: "Are you sure?" }, class:'btn-red link-no-deco' %>
            </div>
          </div>
        </div>
      <% end %>
    <% if @pokemon.user != current_user %>
      <div class="booking-form col-sm-12 col-md-4">
      <h3 class="mb-3">Ready to book <%= @pokemon.name  %>?</h3>
        <%= simple_form_for [@pokemon, @booking], remote: true do |f| %>
          <div class="row">
            <div class="col-sm-12 col-md-6">
              <%= f.input :begin_date, label: "From:", placeholder:"Start date", as: :string, required: false, input_html: {class: "datepicker"} %>
            </div>
            <div class="col-sm-12 col-md-6">
              <%= f.input :end_date, label: "To:", placeholder:"End date", as: :string, required: false, input_html: {class: "datepicker"} %>
            </div>
            <p class="price-align-left mb-0">Day price: <strong id="day-price-value"><%= @pokemon.day_price %></strong>€</p>
            <p class="my-0 price-align-left">__________</p>
            <h4 class="mt-2 mb-3 price-align-left">Total price <strong id="total-price-value"> <%= @booking.total_price %></strong></h4>
          </div>
          <%= f.submit "Book", class: "w-100 btn btn-flat mb-2" %>
          <p class="mb-1 text-center"><small>You won't be charged yet</small></p>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>
</div>